# config/environment.conf
# Shared environment configuration for the AWS Production Web Platform.

AWS_REGION="us-east-1"
PROJECT_NAME="aws-production-web-platform"

VPC_NAME="$PROJECT_NAME-vpc"

PUBLIC_SUBNET_A_NAME="$PROJECT_NAME-public-subnet-az1"
PUBLIC_SUBNET_B_NAME="$PROJECT_NAME-public-subnet-az2"

PRIVATE_APP_SUBNET_A_NAME="$PROJECT_NAME-private-app-subnet-az1"
PRIVATE_APP_SUBNET_B_NAME="$PROJECT_NAME-private-app-subnet-az2"

PRIVATE_DB_SUBNET_A_NAME="$PROJECT_NAME-private-db-subnet-az1"
PRIVATE_DB_SUBNET_B_NAME="$PROJECT_NAME-private-db-subnet-az2"

IGW_NAME="$PROJECT_NAME-igw"

PUBLIC_RT_NAME="$PROJECT_NAME-public-rt"
PRIVATE_APP_RT_A_NAME="$PROJECT_NAME-private-app-rt-a"
PRIVATE_APP_RT_B_NAME="$PROJECT_NAME-private-app-rt-b"
PRIVATE_DB_RT_NAME="$PROJECT_NAME-private-db-rt"

NAT_GW_A_NAME="$PROJECT_NAME-nat-gateway-az1"
NAT_GW_B_NAME="$PROJECT_NAME-nat-gateway-az2"

EIP_A_NAME="$PROJECT_NAME-nat-eip-az1"
EIP_B_NAME="$PROJECT_NAME-nat-eip-az2"

ALB_SG_NAME="$PROJECT_NAME-alb-sg"
APP_SG_NAME="$PROJECT_NAME-app-sg"
DB_SG_NAME="$PROJECT_NAME-db-sg"

EC2_ROLE_NAME="$PROJECT_NAME-ec2-role"
EC2_INSTANCE_PROFILE_NAME="$PROJECT_NAME-ec2-instance-profile"
SSM_MANAGED_POLICY_ARN="arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"

